theme: jekyll-theme-minimal
title: UVA's Public Interest Data Lab
description: Project site for UVA's Spring 2018 Public Interest Data Lab

BASE_PATH : http://username.github.io/PublicInterestData2018
